export const EMAIL_RECIPIENTS = {
  COMMON_CONTETRA: [
    'pankaj.sakpal@contetra.com',
    'tejas.savla@contetra.com',
    'chitra.parameswaran@contetra.com',
    'aastha.varshneya@contetra.com',
    'palak.kedia@contetra.com',
    'kashish.rajpal@contetra.com',
    'ankita.kedare@contetra.com',
    'jay.jani@contetra.com',
    'anuja.shende@contetra.com',
  ],
  KYC: [
    'shuaib.ansari@contetra.com',
    'bhavesh.sonavane@contetra.com',
    'tejas.savla@contetra.com',
    'chitra.parameswaran@contetra.com',
    'palak.kedia@contetra.com',
    'kashish.rajpal@contetra.com',
  ],
  AUTOMATION: [
    'chitra.parameswaran@contetra.com',
    'tejas.savla@contetra.com',
    'aastha.varshneya@contetra.com',
    'ankita.kedare@contetra.com',
    'jay.jani@contetra.com',
    'pankaj.sakpal@contetra.com',
    'palak.kedia@contetra.com',
    'kashish.rajpal@contetra.com',
  ],
};
